latex3/fontspec

- fontspec.dtx
`\tl_gset:cV` and `\prop_gput:cn(V|x)` have been in expl3 since
2011-04-30 (3d377e140abba03da0b749a9d892e9b7eca8c1f1) and
2011-04-27 (f7ff4f7eaaeb7e9e5e73a891ee5b5d03fab8360a), respectively.
As fontspec does
\RequirePackage{expl3}[2011/09/05]
the variant generate can be removed and cuts down log noise.
> Remove redudant variant generation

- fontspec.dtx
Hi, the diff here would enable fontspec to work with the proposed latex  kernel `ltuatex` code without requiring the `emu-luatexbase` luatexbase emulation layer. (A similar pull request has been sent to luaotfload)
> Modify to work out of the box with core ltluatex interface as well as the existing luatexbase interface

- fontspec.dtx
This avoids any issues with having to search for the primitives, but
does require an recent expl3.
> Use expl3 ":D" names for LuaTeX primitives

- fontspec-patches.dtx
Code comments referred to U+2434 where U+2423 was intended.
modified:   fontspec-patches.dtx
> Fix #227: wrong Unicode code point in documentation for visible space

- fontspec-lua.dtx
We need explicit catcode table for tex.sprint(), which may behave
unexpectedly in verbatim environment among others. Addresses #230.
> explicit catcode table for tex.sprint()

- fontspec-xfss.dtx
Boolean expressions will soon change to be eager by default in expl3.
> Use lazy evaluation of booleans explicitly

- fontspec-internal.dtx
- fontspec-keyval.dtx
- fontspec-vars.dtx
Currently, we allocate a new internal integer register for every new font. Personally I think it's kind of a waste. A global property list may be a better way.
> employ property lists to manage the unique identifier of the font

- fontspec-doc-featset.tex
- fontspec-doc-fontsel.tex
`UprightFont` and `UprightFeatures` appear in the document but do not in the lists at II.2.1 and III.3, resp.
> append UprightFont and UprightFeatures to the lists in the document [ci skip]

- fontspec-code-keyval.dtx
- fontspec-code-msg.dtx
- fontspec-doc-featset.tex
Both harfload and next version of luaotfload are going to support it.
With old version of these package the option will be silently ignored, but that should be a minor issue as the final document will be the same as before.
> Allow FakeBold with LuaTeX

- fontspec-code-internal.dtx
**READY**
Always add `\l_@@_pre_feat_sclist` features when loading a font.
The main motivation is HarfBuzz support in LuaTeX: The current approach loads HarfBuzz font without `mode=harf` first, forcing the traditional fontloader to load the font. This is a problem especially for very big fonts for which caching can be very slow using the ConTeXt fontloader.
This fixes that by passing all features in `\l_@@_pre_feat_sclist` for all font requests, leaving no font load without mode parameter.
- n/a Documentation if necessary
For example the following file should compile significantly faster and with much less memory usage if "Noto Serif CJK KR" isn't already cached.
```
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Noto Serif CJK KR}[
Renderer = Harfbuzz,
] …
```
> Always add some font features

- fontspec-code-internal.dtx
- fontspec-code-msg.dtx
**READY**
Basically `\@@_load_fontname:Nn` called `\@@_load_external_fontoptions:Nn #1 {#2}` without setting `#1` first and relied on `#1` being set afterwards. This assumption broke when the font was loaded with `IgnoreFontspecFile` which turns `\@@_load_external_fontoptions:Nn #1 {#2}` into a no-op.
This could be fixed by always setting `#1` in `\@@_load_external_fontoptions:Nn`, even if `IgnoreFontspecFile` is used, but I considered it cleaner to do it outside because it's not really related to loading the fontoptions. At that point there is no longer a real need to even pass `#2` to `\@@_load_external_fontoptions:Nn` since it can be read from `#1` anyway, so the function became `\@@_load_external_fontoptions:N`.
(This is the bug causing …
> Do not rely on load_external_fontoptions side-effects / Fix IgnoreFontspecFile

- fontspec-code-internal.dtx
- fontspec-code-keyval.dtx
- fontspec-code-vars.dtx
- fontspec-doc-fontsel.tex
**READY**
Add an option `KpseOnly` to restrict font searches to fonts in the TeX directories as discussed in #413.
In XeTeX the option works too but is ignored.
```
\documentclass{article}
\usepackage{unicode-math}
\setmainfont{texgyrepagella}[
KpseOnly,
Extension = .otf ,
UprightFont = *-regular.otf ,
ItalicFont  = *-italic.otf  ,
]
hello \emph{hello}
\end{document}
```
> Implement OnlyKpse for LuaTeX

- fontspec-code-internal.dtx
- testfiles/fontload-fontname.luatex.tlg
- testfiles/fontload-fontname.lvt
- testfiles/fontload-fontname.tlg
**READY**
Use luaotfload's name: lookup for fontname based lookups instead of letting luaotfload guess. This is faster and more reliable if other files with problematic names are lying around.
Fixes #442.
- n/a Documentation if necessary
```
\documentclass{article}
\usepackage{unicode-math}
\setmainfont{texgyrepagella}
Should now start with \texttt{name:}: \fontname \font
\end{document}
```
> Use explicit name: lookups for LuaTeX

- testfiles/script-lang-trk.luatex.tlg
- testfiles/script-lang-trk.lvt
- testfiles/script-lang-trk.tlg
**READY**
See #465: Call the font with the name STIXTwoText instead of STIX2Text to match the official filename.
- n/a Tests added to cover new/fixed functionality
- n/a Documentation if necessary
- n/a Code follows expl3 style guidelines
> Use STIXTwo instead of STIX2 in tests

- CHANGES.md
- fontspec-code-load.dtx
- fontspec-code-msg.dtx
- fontspec-code-opening.dtx
- fontspec-code-vars.dtx
- fontspec-doc-intro.tex
- fontspec.ins
- testfiles/00-pkg-load-twice.luatex.tlg
- testfiles/00-pkg-load-twice.lvt
- testfiles/00-pkg-load-twice.tlg
**READY**
* changes the package option to the new keyval-handler to avoid option clash errors.
* removed the euenc code
* made the euenc and tuenc option obsolete.
```
\documentclass{article}
\usepackage{fontspec}
\usepackage[no-math]{fontspec}
hello $\mathrm{a}$ 
\end{document}
```
> Use keyval for package options

- CHANGES.md
- fontspec-code-keyval.dtx
- fontspec-doc-featset.tex
- testfiles/feat-scale-match.luatex.tlg
- testfiles/feat-scale-match.lvt
- testfiles/feat-scale-match.tlg
**READY**
I have added a `Scale=MatchAveragecase` option to complement `Scale=MatchLowercase` and `Scale=MatchUppercase`, it simply sets the Scale to the average of what `MatchLowercase` and `MatchUppercase` would do. This is usefull when you can't make up your mind whether to use `MatchLowercase` or `MatchUppercase`, or when neither looks good, as in the example below (where in my opinion, the `MatchAveragecase` version looks the best)
```
\setmainfont{TeXGyreSchola}
\newfontfamily\lc[Scale=MatchLowercase]{Fira Math}
\newfontfamily\uc[Scale=MatchUppercase]{Fira Math}
\newfontfamily\ac[Scale=MatchAveragecase]{Fira Math}
\noindent
Lower {\lc and UPPER} CASE\\
Lower {\uc and UPPER} CASE\\
Lower {\ac and UPPER} CASE
\end{document}
```
> Added a Scale=MatchAveragecase option

- fontspec-doc-fontsel.tex
- fontspec-doc-intro.tex
**READY**
+ Fix several typos
+ Add `\DescribeOption` for quicker search in the margin area
> Fix typos and add \DescribeOption in the documentation

- fontspec-code-internal.dtx
- fontspec-code-keyval.dtx
For discussion.
Potential fix for bug #436.
I do *not* claim this is the correct fix, in fact I'm pretty sure it is not. My intention is to draw attention to this 19 month old bug report and offer a possible explanation for what is going wrong, because it also affects me and I would like to see it fixed.
I have no clue whatsoever about LaTeX 3 code, keyval, or anything else; my expertise *just* reaches `s/preparse/opentype/` as shown here.
See bug #436.
> Make *Features work in \defaultfontfeatures

- fontspec-code-feat-opentype.dtx
- fontspec-doc-opentype.tex
**READY**
Expose `luaotfload`'s support for casemapping through the `Letters = Uppercase` / `Letters = Lowercase` features.
This allows to convert text to upper or lowercase on the font level and therefore avoids requiring the mapped content tp be expandable or similar. Additionally this allows to reuse the selected language of a font for applying properly tailored mappings.
Maybe the most interesting aspects:
1. LuaTeX only.
2. In addition to triggering the case maping itself, `Letters = Uppercase` automatically applies the equivalent of `Style = Uppercase` and `Kerning = Uppercase`. The idea is that these features are designed to be enabled for uppercase text, so if the text is mapped to uppercase it is a reasonable default to enable them.
3. This reuses the `Letters = Uppercase` name …
> Case mapping for LuaLaTex

- fontspec-code-internal.dtx
- fontspec-code-keyval.dtx
- fontspec-code-opening.dtx
- fontspec-code-xfss.dtx
**READY**
This PR drops function variant generations that are already provided in recent `expl3` (aka `l3kernel`), and changes relevant uses of `x`-type expansion to `e`-type.
A whole `x`-to-`e` switch can be done later in separate commit/PR.
> Tidy up variants of expl3 functions

- .github/workflows/doc.yaml
- .github/workflows/main.yaml
- doc/CHANGES.md
- fontspec-code-opening.dtx
- fontspec-code-xfss.dtx
- testfiles/support/fontspec-testsetup.tex
**READY**
Replace (soft-)deprecated l3kernel `\prop_gput_if_new:Nnn` with `\prop_gput_if_not_in:Nnn`, see
- latex3/latex3@a4f84501 (Rename \prop_(g)put_if_new:Nn to \prop_(g)put_if_not_in:Nn, 2024-03-30) and
- latex3/latex3@a4390cc9 (Avoid warnings for use of \prop_put_if_new: A temporary change until fontspec is updated., 2024-04-06)
> Re-sync with `expl3` for deprecated commands
